'use strict';

module.exports = {
  serverError: 'Internal Server Error',
  validationErrors: 'Validation Errors',
  notFoundError: 'Method or URL Not Found',
  authorizationRequired: 'Authorization Required',
  tokenExpired: 'Token Expired',
  invalidPermission: 'Unauthorized',
  emailSentError: 'Couldn\'t Send Email',
  smsSentError: 'Couldn\'t Send SMS',
  signupSuccess: 'Successfully Signed Up',
  otpSendSuccess: 'OTP sent successfully',
  incorrectOtp: 'Incorrect OTP',
  incorrectEmailOtp: 'Incorrect email OTP',
  invalidLoginCredentials: 'Not a valid email or password',
  loginSuccess: 'Successfully Logged In',
  sentForgotOtp: 'If you are a registered user, a verification code ' +
    'will be sent to the email address provided to reset your password',
  invalidEmail: 'Not a valid email',
  resetPasswordSuccess: 'Password Reset Successfully',
  sellerNotFound: 'Seller Not Found',
  sellerNotMatching: 'Seller Not Matching',
  usersFetched: 'Fetched Users',
  userNotFound: 'User Not Found',
  userFetched: 'Fetched User',
  userExists: 'User Already Exists with this email or phone',
  userCreated: 'Created User',
  userUpdated: 'Updated User',
  userDeleted: 'Deleted User',
  sellerExist: 'Seller Already Exists with this email',
  incorrectPassword: 'Incorrect Password',
  changePasswordSuccess: 'Password Changed Successfully',
  logoutSuccess: 'Successfully Logged Out',
  fcmTokenAdded: 'Added FCM Token',
  profileFetched: 'Fetched Profile',
  profileUpdated: 'Updated Profile',
  timeSlotAdded: 'Time Slot Added',
  timeSlotOverlap: 'time slot is overlapping with another one',
  timeSlotDeleted: 'Time slot deleted',
  timeslotNotFound: 'Time slot not found',
  appointmentRequestSent: 'Appointment Request Sent',
  appointmentRequestExist: 'Appointment Request Exist',
  appointmentsFetched: 'Appointments Fetched',
  appointmentRequestNotFound: 'Appointment Request Not Found',
  notPendingStatus: 'not pending status',
  appointmentStatusChanged: 'Appointment Status Changed',
  noRemainingAppointments: 'No remaining appointments',
  sellerFetched: 'Seller fetched',
  appointmentRequestFetched: 'Appointment request fetched',
};
